comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

coverage: # https://docs.codecov.com/docs/codecovyml-reference#coverage
  precision: 5
  range:
    - 80.0
    - 85.0
  status:
    project:
      default:
        branches:
          - ^main$
        target: 80.0 # the minimum coverage ratio that the commit must meet to be considered a success.
        threshold: 1% # allow the coverage to drop by X%, and posting a success status.