comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

coverage: # https://docs.codecov.com/docs/codecovyml-reference#coverage
  precision: 5
  range: "80...100"
  status:
    project:
      default:
        branches:
          - ^JDK17/Springboot3$
        target: 80.0
        threshold: 1%
  ignore:
    - "**/test/**"
    - "**/*Test.java"
    - "**/*AuthCenter.java"
    - "**/*QappPackage.java"
    - "**/*TRPCProtocol.java"
parsers:
  jacoco:
    partials_as_hits: true