/*
 * Tencent is pleased to support the open source community by making tRPC available.
 *
 * Copyright (C) 2023 THL A29 Limited, a Tencent company. 
 * All rights reserved.
 *
 * If you have downloaded a copy of the tRPC source code from Tencent,
 * please note that tRPC source code is licensed under the Apache 2.0 License,
 * A copy of the Apache 2.0 License can be found in the LICENSE file.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trpc.proto

package com.tencent.trpc.codegen.extension;

public final class TrpcExtensionProto {
  private TrpcExtensionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(TrpcExtensionProto.alias);
    registry.add(TrpcExtensionProto.goTag);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int ALIAS_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      String> alias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int GO_TAG_FIELD_NUMBER = 50050;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> goTag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntrpc.proto\022\004trpc\032 google/protobuf/desc" +
      "riptor.proto:/\n\005alias\022\036.google.protobuf." +
      "MethodOptions\030\321\206\003 \001(\t:/\n\006go_tag\022\035.google" +
      ".protobuf.FieldOptions\030\202\207\003 \001(\tB8\n\"com.te" +
      "ncent.trpc.codegen.extensionB\022TrpcExtens" +
      "ionProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    alias.internalInit(descriptor.getExtensions().get(0));
    goTag.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
